//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_LAB_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAB_H2O_TANK_DATA
    {
        public Nullable<System.DateTime> H2ODATE { get; set; }
        public Nullable<int> H2ONORTH0000 { get; set; }
        public Nullable<int> H2ONORTH0600 { get; set; }
        public Nullable<int> H2ONORTH1200 { get; set; }
        public Nullable<int> H2ONORTH1800 { get; set; }
        public Nullable<int> H2OSOUTH0000 { get; set; }
        public Nullable<int> H2OSOUTH0600 { get; set; }
        public Nullable<int> H2OSOUTH1200 { get; set; }
        public Nullable<int> H2OSOUTH1800 { get; set; }
        public int H2O_ID { get; set; }
        public Nullable<int> H2ONO5_0600 { get; set; }
        public Nullable<int> H2ONO5_1200 { get; set; }
        public Nullable<int> H2ONO5_1800 { get; set; }
        public Nullable<int> H2ONO5_0000 { get; set; }
    }
}
