//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_LAB_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAB_KILN_DRYER
    {
        public Nullable<System.DateTime> KDDATE { get; set; }
        public Nullable<decimal> KFLS0600_1 { get; set; }
        public Nullable<decimal> KFLS0600_2 { get; set; }
        public Nullable<decimal> KFLS0600_3 { get; set; }
        public Nullable<decimal> KFLS1800_1 { get; set; }
        public Nullable<decimal> KFLS1800_2 { get; set; }
        public Nullable<decimal> KFLS1800_3 { get; set; }
        public Nullable<decimal> KFM0600_1 { get; set; }
        public Nullable<decimal> KFM0600_2 { get; set; }
        public Nullable<decimal> KFM0600_3 { get; set; }
        public Nullable<decimal> KDLOI2200_1 { get; set; }
        public Nullable<decimal> KDLOI2200_2 { get; set; }
        public Nullable<decimal> KDLOI2200_3 { get; set; }
        public Nullable<decimal> KDLOI1000_1 { get; set; }
        public Nullable<decimal> KDLOI1000_2 { get; set; }
        public Nullable<decimal> KDLOI1000_3 { get; set; }
        public Nullable<decimal> KDNA2200_1 { get; set; }
        public Nullable<decimal> KDNA2200_2 { get; set; }
        public Nullable<decimal> KDNA2200_3 { get; set; }
        public Nullable<decimal> KDNA1000_1 { get; set; }
        public Nullable<decimal> KDNA1000_2 { get; set; }
        public Nullable<decimal> KDNA1000_3 { get; set; }
        public Nullable<decimal> KDCA2200_1 { get; set; }
        public Nullable<decimal> KDCA2200_2 { get; set; }
        public Nullable<decimal> KDCA2200_3 { get; set; }
        public Nullable<decimal> KDCA1000_1 { get; set; }
        public Nullable<decimal> KDCA1000_2 { get; set; }
        public Nullable<decimal> KDCA1000_3 { get; set; }
        public Nullable<decimal> KDZN2200_1 { get; set; }
        public Nullable<decimal> KDZN2200_2 { get; set; }
        public Nullable<decimal> KDZN2200_3 { get; set; }
        public Nullable<decimal> KDZN1000_1 { get; set; }
        public Nullable<decimal> KDZN1000_2 { get; set; }
        public Nullable<decimal> KDZN1000_3 { get; set; }
        public Nullable<decimal> HD0600LS { get; set; }
        public Nullable<decimal> HD0600RF { get; set; }
        public Nullable<decimal> HD1100LS { get; set; }
        public Nullable<decimal> HD1100RF { get; set; }
        public Nullable<decimal> HD1800LS { get; set; }
        public Nullable<decimal> HD1800RF { get; set; }
        public Nullable<decimal> HD2200LS { get; set; }
        public Nullable<decimal> HD2200RF { get; set; }
        public Nullable<decimal> HDFM0600 { get; set; }
        public Nullable<decimal> PSMAPFNA { get; set; }
        public Nullable<decimal> PSMAPFCA { get; set; }
        public Nullable<decimal> PSMAPFZN { get; set; }
        public Nullable<decimal> PSMA6A6BNA { get; set; }
        public Nullable<decimal> PSMA6A6BCA { get; set; }
        public Nullable<decimal> PSMA6A6BZN { get; set; }
        public Nullable<decimal> PSMATTSNA { get; set; }
        public Nullable<decimal> PSMATTSCA { get; set; }
        public Nullable<decimal> PSMATTSZN { get; set; }
        public Nullable<decimal> PSMASTSNA { get; set; }
        public Nullable<decimal> PSMASTSCA { get; set; }
        public Nullable<decimal> PSMASTSZN { get; set; }
        public Nullable<decimal> KFM { get; set; }
        public Nullable<decimal> KFM2 { get; set; }
        public Nullable<decimal> KFM3 { get; set; }
        public Nullable<decimal> CPNNA { get; set; }
        public Nullable<decimal> CPNCA { get; set; }
        public Nullable<decimal> CPNZN { get; set; }
        public Nullable<decimal> CPSNA { get; set; }
        public Nullable<decimal> CPSCA { get; set; }
        public Nullable<decimal> CPSZN { get; set; }
        public Nullable<decimal> FT6 { get; set; }
        public int KILN_ID { get; set; }
    }
}
