//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_LAB_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAB_SEC1_DATA
    {
        public Nullable<System.DateTime> SDDATE { get; set; }
        public Nullable<decimal> SASUF { get; set; }
        public Nullable<decimal> SAWUF { get; set; }
        public Nullable<decimal> SAMTL { get; set; }
        public Nullable<decimal> SAFA { get; set; }
        public Nullable<decimal> SALR { get; set; }
        public Nullable<decimal> GPLS1 { get; set; }
        public Nullable<decimal> GPLS2 { get; set; }
        public Nullable<decimal> GPLS3 { get; set; }
        public Nullable<decimal> GPLS4 { get; set; }
        public Nullable<decimal> GPLSBF { get; set; }
        public Nullable<decimal> GPLSOXSET { get; set; }
        public Nullable<decimal> SABF { get; set; }
        public Nullable<decimal> SAOXSET { get; set; }
        public Nullable<decimal> SALIMEREC { get; set; }
        public Nullable<decimal> SAST { get; set; }
        public Nullable<decimal> SALP { get; set; }
        public Nullable<decimal> OAOXSET { get; set; }
        public Nullable<decimal> OABF { get; set; }
        public Nullable<decimal> OA1CAKE { get; set; }
        public Nullable<decimal> OA2CAKE { get; set; }
        public Nullable<decimal> OASTSEED { get; set; }
        public Nullable<decimal> OA6AB { get; set; }
        public Nullable<decimal> OAPF { get; set; }
        public Nullable<decimal> SRS { get; set; }
        public Nullable<decimal> SRSTARCHI { get; set; }
        public Nullable<decimal> SRSTARCHS { get; set; }
        public Nullable<decimal> SRPF { get; set; }
        public Nullable<decimal> TAAA4FT { get; set; }
        public Nullable<decimal> TAAASF { get; set; }
        public Nullable<decimal> TAAASUF { get; set; }
        public Nullable<decimal> TAAAWUF { get; set; }
        public Nullable<decimal> TAAAMTL { get; set; }
        public Nullable<decimal> LTPCA { get; set; }
        public Nullable<decimal> LTP { get; set; }
        public Nullable<decimal> SPENTLIQ { get; set; }
        public Nullable<decimal> Y1516 { get; set; }
        public Nullable<decimal> TRIDIGEST { get; set; }
        public Nullable<decimal> FT5 { get; set; }
        public Nullable<decimal> DIGDISCH { get; set; }
        public Nullable<decimal> WP0 { get; set; }
        public Nullable<decimal> WP1 { get; set; }
        public Nullable<decimal> WP2 { get; set; }
        public Nullable<decimal> WP3 { get; set; }
        public Nullable<decimal> WP4 { get; set; }
        public Nullable<decimal> WP5 { get; set; }
        public Nullable<decimal> WP6 { get; set; }
        public Nullable<decimal> WP7 { get; set; }
        public Nullable<decimal> WP8 { get; set; }
        public Nullable<decimal> TD { get; set; }
        public Nullable<decimal> CPDS1 { get; set; }
        public Nullable<decimal> CPDS2 { get; set; }
        public Nullable<decimal> CPDS3 { get; set; }
        public Nullable<decimal> CPDS4 { get; set; }
        public Nullable<decimal> CRETTANK { get; set; }
        public Nullable<decimal> APDS1 { get; set; }
        public Nullable<decimal> APDS2 { get; set; }
        public Nullable<decimal> APDS3 { get; set; }
        public Nullable<decimal> APDS4 { get; set; }
        public Nullable<decimal> ARETTANK { get; set; }
        public Nullable<decimal> SPDS1 { get; set; }
        public Nullable<decimal> SPDS2 { get; set; }
        public Nullable<decimal> SPDS3 { get; set; }
        public Nullable<decimal> SPDS4 { get; set; }
        public Nullable<decimal> SRETTANK { get; set; }
        public Nullable<decimal> DRETTANK { get; set; }
        public Nullable<decimal> D1PDS { get; set; }
        public Nullable<decimal> D2PDS { get; set; }
        public Nullable<decimal> D3PDS { get; set; }
        public Nullable<decimal> D4PDS { get; set; }
        public int SECI_ID { get; set; }
    }
}
