//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_LAB_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAB_WETCAKE_BARGE
    {
        public string CERTIFICATE_ID { get; set; }
        public string BARGE_ID { get; set; }
        public string LOADOUT_DATE { get; set; }
        public string SIO2 { get; set; }
        public string FE2O3 { get; set; }
        public string NA2O { get; set; }
        public string CAO { get; set; }
        public string C_SEDS { get; set; }
        public string A_INSOLS { get; set; }
        public string L_SODA { get; set; }
        public string P100 { get; set; }
        public string P200 { get; set; }
        public string P325 { get; set; }
        public string REFLECTANCE { get; set; }
        public string SOLIDS { get; set; }
        public string HUNTER_L { get; set; }
        public string HUNTER_A { get; set; }
        public string HUNTER_B { get; set; }
        public int WC_ID { get; set; }
    }
}
