//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_LAB_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAB_ENVIRONMENTAL
    {
        public Nullable<System.DateTime> EADATE { get; set; }
        public Nullable<decimal> RWRPH { get; set; }
        public Nullable<decimal> EDPH { get; set; }
        public Nullable<decimal> WDPH { get; set; }
        public Nullable<decimal> FEDPH { get; set; }
        public Nullable<decimal> CDPH { get; set; }
        public Nullable<decimal> OXPOND { get; set; }
        public Nullable<decimal> EDFLOW { get; set; }
        public Nullable<decimal> WDFLOW { get; set; }
        public Nullable<decimal> FEDFLOW { get; set; }
        public Nullable<decimal> CDFLOW { get; set; }
        public Nullable<decimal> SEWERPH1 { get; set; }
        public Nullable<decimal> SEWERPH2 { get; set; }
        public Nullable<decimal> SEWERPH3 { get; set; }
        public Nullable<decimal> SEWERPH5 { get; set; }
        public Nullable<decimal> DAMPH1 { get; set; }
        public Nullable<decimal> SAHOTWELL { get; set; }
        public Nullable<decimal> SAPLANTDRAIN { get; set; }
        public Nullable<decimal> SALIFTSTATION { get; set; }
        public Nullable<decimal> SASURGEBASIN { get; set; }
        public Nullable<decimal> P2O5CATESTTANK { get; set; }
        public Nullable<decimal> P2O5CASETTLERFEED { get; set; }
        public Nullable<decimal> ABSCATESTTANK { get; set; }
        public Nullable<decimal> ABSCALTP { get; set; }
        public Nullable<decimal> SCATESTTANK { get; set; }
        public Nullable<decimal> SCA4FT { get; set; }
        public Nullable<decimal> SCASETTLERFD { get; set; }
        public Nullable<decimal> SCALTP { get; set; }
        public Nullable<decimal> FASETTLER { get; set; }
        public Nullable<decimal> FAWASHER { get; set; }
        public Nullable<decimal> FAMIDDLE { get; set; }
        public int ENV_ID { get; set; }
    }
}
