//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_LAB_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAB_DAILY_OP_Sample_Inventory
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Shift { get; set; }
        public Nullable<int> WOF { get; set; }
        public string WOF_comments { get; set; }
        public Nullable<int> SUF { get; set; }
        public string SUF_comments { get; set; }
        public Nullable<int> WUF { get; set; }
        public string WUF_comments { get; set; }
        public Nullable<int> MTL { get; set; }
        public string MTL_comments { get; set; }
        public Nullable<int> SRT { get; set; }
        public string SRT_comments { get; set; }
        public Nullable<int> Washer_Profile { get; set; }
        public string WP_comments { get; set; }
        public Nullable<int> Sulfide_Tank { get; set; }
        public string Sulfide_Tank_Cmt { get; set; }
        public Nullable<int> Lime_Recovery { get; set; }
        public string Lime_Recovery_Cmt { get; set; }
        public Nullable<int> Filter_Aid { get; set; }
        public string Filter_Aid_Cmt { get; set; }
        public Nullable<int> Dilution_Floc { get; set; }
        public string Dilution_Floc_Cmt { get; set; }
        public Nullable<int> TT_Tops { get; set; }
        public string TT_Tops_Cmt { get; set; }
        public Nullable<int> ST_Tops { get; set; }
        public string ST_Tops_Cmt { get; set; }
        public Nullable<int> ST_38 { get; set; }
        public string ST_38_Cmt { get; set; }
        public Nullable<int> TT_52 { get; set; }
        public string TT_52_Cmt { get; set; }
        public Nullable<int> A6_UF { get; set; }
        public string A6_UF_Cmt { get; set; }
        public Nullable<int> B6_UF { get; set; }
        public string B6_UF_Cmt { get; set; }
        public Nullable<int> A7_UF { get; set; }
        public string A7_UF_Cmt { get; set; }
        public Nullable<int> B7_UF { get; set; }
        public string B7_UF_Cmt { get; set; }
        public Nullable<int> A7_OF { get; set; }
        public string A7_OF_Cmt { get; set; }
        public Nullable<int> B7_OF { get; set; }
        public string B7_OF_Cmt { get; set; }
        public Nullable<int> Y15_UF { get; set; }
        public string Y15_UF_Cmt { get; set; }
        public Nullable<int> Y16_UF { get; set; }
        public string Y16_UF_Cmt { get; set; }
        public Nullable<int> Y15_OF { get; set; }
        public string Y15_OF_Cmt { get; set; }
        public Nullable<int> Y16_OF { get; set; }
        public string Y16_OF_Cmt { get; set; }
        public Nullable<int> C_1b_Cake { get; set; }
        public string C_1b_Cake_Cmt { get; set; }
        public Nullable<int> C_2b_Cake { get; set; }
        public string C_2b_Cake_Cmt { get; set; }
        public Nullable<int> B_Filtrate_Cyc { get; set; }
        public string B_Filtrate_Cyc_Cmt { get; set; }
        public Nullable<int> Tray_OF { get; set; }
        public string Tray_OF_Cmt { get; set; }
        public Nullable<int> Kiln_Feed { get; set; }
        public string Kiln_Feed_Cmt { get; set; }
        public Nullable<int> Dryer_Feed { get; set; }
        public string Dryer_Feed_Cmt { get; set; }
        public Nullable<int> Kiln_Discharge { get; set; }
        public string Kiln_Discharge_Cmt { get; set; }
        public Nullable<int> Dryer_Discharge { get; set; }
        public string Dryer_Discharge_Cmt { get; set; }
        public Nullable<int> North_Fresh { get; set; }
        public string North_Fresh_Cmt { get; set; }
        public Nullable<int> South_Fresh { get; set; }
        public string South_Fresh_Cmt { get; set; }
        public Nullable<int> No5 { get; set; }
        public string No5_Cmt { get; set; }
    }
}
