//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_LAB_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAB_MISC
    {
        public Nullable<System.DateTime> MMISCDATE { get; set; }
        public string MMISCDESCR { get; set; }
        public string MMISCQTY { get; set; }
        public string MMISCSIZE { get; set; }
        public int MD_ID { get; set; }
        public string CCROUND { get; set; }
    }
}
