//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_LAB_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAB_DAILYANALYSIS
    {
        public Nullable<System.DateTime> DADATE { get; set; }
        public string PRODUCT { get; set; }
        public Nullable<decimal> LOI { get; set; }
        public Nullable<decimal> P100 { get; set; }
        public Nullable<decimal> P200 { get; set; }
        public Nullable<decimal> P325 { get; set; }
        public Nullable<decimal> BULKDENS { get; set; }
        public Nullable<decimal> SI { get; set; }
        public Nullable<decimal> FE { get; set; }
        public Nullable<decimal> NA { get; set; }
        public Nullable<decimal> ZN { get; set; }
        public Nullable<decimal> MN { get; set; }
        public Nullable<decimal> CA { get; set; }
        public Nullable<decimal> TI { get; set; }
        public Nullable<decimal> FREEMOIST { get; set; }
        public Nullable<decimal> CSEDS { get; set; }
        public Nullable<decimal> INSOLS { get; set; }
        public Nullable<decimal> HUNTERL { get; set; }
        public Nullable<decimal> HUNTERA { get; set; }
        public Nullable<decimal> HUNTERB { get; set; }
        public Nullable<decimal> AI { get; set; }
        public Nullable<decimal> M20 { get; set; }
        public int DAILY_ID { get; set; }
    }
}
