//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_LAB_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAB_CHARGECONTROL
    {
        public string CCROUND { get; set; }
        public Nullable<System.DateTime> CCDATE { get; set; }
        public Nullable<decimal> PLANTCS { get; set; }
        public Nullable<decimal> TESTTANKCAUSTIC { get; set; }
        public Nullable<decimal> TESTTANKAC { get; set; }
        public Nullable<decimal> FLASHTANK4CAUSTIC { get; set; }
        public Nullable<decimal> FLASHTANK4AC { get; set; }
        public Nullable<decimal> SETTLERFEEDCAUSTIC { get; set; }
        public Nullable<decimal> SETTLERFEEDAC { get; set; }
        public Nullable<decimal> PRESSFEEDCAUSTIC { get; set; }
        public Nullable<decimal> PRESSFEEDAC { get; set; }
        public Nullable<decimal> LTPCAUSTIC { get; set; }
        public Nullable<decimal> LTPAC { get; set; }
        public Nullable<decimal> EVAPFEEDCAUSTIC { get; set; }
        public Nullable<decimal> EVAPFEEDAC { get; set; }
        public Nullable<decimal> A7OVERFLOWCAUSTIC { get; set; }
        public Nullable<decimal> A7OVERFLOWAC { get; set; }
        public Nullable<decimal> B7OVERFLOWCAUSTIC { get; set; }
        public Nullable<decimal> B7OVERFLOWAC { get; set; }
        public Nullable<decimal> T1CAUSTIC { get; set; }
        public Nullable<decimal> T1AC { get; set; }
        public Nullable<decimal> T3CAUSTIC { get; set; }
        public Nullable<decimal> T3AC { get; set; }
        public Nullable<decimal> T7CAUSTIC { get; set; }
        public Nullable<decimal> T7AC { get; set; }
        public Nullable<decimal> EVAPDISCH1CAUSTIC { get; set; }
        public Nullable<decimal> EVAPDISCH1AC { get; set; }
        public Nullable<decimal> EVAPDISCH2CAUSTIC { get; set; }
        public Nullable<decimal> EVAPDISCH2AC { get; set; }
        public Nullable<decimal> LTV1CAUSTIC { get; set; }
        public Nullable<decimal> LTV1AC { get; set; }
        public Nullable<decimal> WOFCAUSTIC { get; set; }
        public Nullable<decimal> WOFAC { get; set; }
        public Nullable<decimal> SUFCAUSTIC { get; set; }
        public Nullable<decimal> SUFAC { get; set; }
        public Nullable<decimal> EVAPCCCAUSTIC { get; set; }
        public Nullable<decimal> EVAPCCAC { get; set; }
        public Nullable<decimal> PRESSCCCAUSTIC { get; set; }
        public Nullable<decimal> PRESSCCAC { get; set; }
        public Nullable<decimal> LKD4SODA { get; set; }
        public Nullable<decimal> WUFSODA { get; set; }
        public Nullable<decimal> MTLSODA { get; set; }
        public Nullable<decimal> SRTSODA { get; set; }
        public Nullable<decimal> CANYONSODA { get; set; }
        public Nullable<decimal> PISOLITESODA { get; set; }
        public Nullable<decimal> PFMG { get; set; }
        public Nullable<decimal> TESTTANKCS { get; set; }
        public Nullable<decimal> SETTLERFEEDCS { get; set; }
        public Nullable<decimal> SETTLERFEEDAIM { get; set; }
        public Nullable<decimal> LTPAIM { get; set; }
        public Nullable<decimal> CTRIDIGESTOR { get; set; }
        public Nullable<decimal> ACTRIDIGESTOR { get; set; }
        public Nullable<decimal> CFT5 { get; set; }
        public Nullable<decimal> ACFT5 { get; set; }
        public Nullable<decimal> CDIGDISCH { get; set; }
        public Nullable<decimal> ACDIGDISCH { get; set; }
        public Nullable<decimal> CEVAPDISCH { get; set; }
        public Nullable<decimal> ACEVAPDISCH { get; set; }
        public Nullable<decimal> CY15OVERFLOW { get; set; }
        public Nullable<decimal> ACY15OVERFLOW { get; set; }
        public Nullable<decimal> CY16OVERFLOW { get; set; }
        public Nullable<decimal> ACY16OVERFLOW { get; set; }
        public Nullable<decimal> TRIDIGESTORAIM { get; set; }
        public Nullable<decimal> FT5AIM { get; set; }
        public Nullable<decimal> CAG1 { get; set; }
        public Nullable<decimal> CAG3 { get; set; }
        public Nullable<decimal> CAG7 { get; set; }
        public Nullable<decimal> ACAG1 { get; set; }
        public Nullable<decimal> ACAG3 { get; set; }
        public Nullable<decimal> ACAG7 { get; set; }
        public Nullable<int> CH_ID { get; set; }
        public Nullable<decimal> FT5CS { get; set; }
        public Nullable<decimal> TRIDIGESTORCS { get; set; }
        public Nullable<decimal> DIGDISCHCS { get; set; }
        public int CC_ID { get; set; }
        public Nullable<decimal> BADCOND { get; set; }
        public Nullable<int> PSCOLOR { get; set; }
    }
}
