//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_LAB_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lab_TagTable
    {
        public int Id { get; set; }
        public string Tag_Name { get; set; }
        public Nullable<decimal> Min { get; set; }
        public Nullable<decimal> Max { get; set; }
        public string Pi_Tags { get; set; }
        public string Pi_Tags_Test { get; set; }
        public string gv_control_name { get; set; }
        public int Indx { get; set; }
    }
}
