//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_LAB_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAB_CAUSTIC_CLEAN
    {
        public string CC_ID { get; set; }
        public Nullable<System.DateTime> CCDATE { get; set; }
        public string CCTRUCK { get; set; }
        public Nullable<decimal> CCCAUSTIC { get; set; }
        public Nullable<decimal> CCAC { get; set; }
        public int CCID { get; set; }
        public string CCROUND { get; set; }
    }
}
