//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_LAB_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAB_SEC_III_DATA
    {
        public Nullable<int> SE_ID { get; set; }
        public Nullable<System.DateTime> SECDATE { get; set; }
        public string SECRECORD { get; set; }
        public string SECID { get; set; }
        public Nullable<int> P100 { get; set; }
        public Nullable<int> P200 { get; set; }
        public Nullable<int> P325 { get; set; }
        public Nullable<int> UM { get; set; }
        public Nullable<int> P325SA { get; set; }
        public Nullable<int> CAUS { get; set; }
        public Nullable<decimal> AC { get; set; }
        public Nullable<decimal> SOL { get; set; }
        public Nullable<int> GPLSOL { get; set; }
        public Nullable<decimal> HT { get; set; }
        public Nullable<int> SA { get; set; }
        public Nullable<decimal> UM20 { get; set; }
        public string INDX { get; set; }
        public int SECIII_ID { get; set; }
    }
}
