//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_LAB_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAB_HOUSEKEEPING
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Shift { get; set; }
        public Nullable<short> BenchTop { get; set; }
        public Nullable<short> Trash { get; set; }
        public Nullable<short> MSHAWorkSheet { get; set; }
        public Nullable<short> MissingLabSamples { get; set; }
        public Nullable<short> SampleDiscarded { get; set; }
        public string EquipmentOOS { get; set; }
        public string OOSSamples { get; set; }
        public Nullable<int> Tech { get; set; }
        public Nullable<int> LabSumpPump1 { get; set; }
        public Nullable<int> LabSumpPump2 { get; set; }
        public Nullable<int> EmailsRead { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
