//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_LAB_project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LabEntities : DbContext
    {
        public LabEntities()
            : base("name=LabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LAB_CAUSTIC_CLEAN> LAB_CAUSTIC_CLEAN { get; set; }
        public virtual DbSet<LAB_CHARGECONTROL> LAB_CHARGECONTROL { get; set; }
        public virtual DbSet<LAB_ENVIRONMENTAL> LAB_ENVIRONMENTAL { get; set; }
        public virtual DbSet<LAB_H2O_TANK_DATA> LAB_H2O_TANK_DATA { get; set; }
        public virtual DbSet<LAB_KILN_DRYER> LAB_KILN_DRYER { get; set; }
        public virtual DbSet<LAB_SEC_III_DATA> LAB_SEC_III_DATA { get; set; }
        public virtual DbSet<LAB_SEC1_DATA> LAB_SEC1_DATA { get; set; }
        public virtual DbSet<LAB_MISC> LAB_MISC { get; set; }
        public virtual DbSet<LAB_WETCAKE_BARGE> LAB_WETCAKE_BARGE { get; set; }
        public virtual DbSet<LAB_REPORT_NAMES> LAB_REPORT_NAMES { get; set; }
        public virtual DbSet<LAB_DAILYANALYSIS> LAB_DAILYANALYSIS { get; set; }
        public virtual DbSet<Lab_TagTable> Lab_TagTable { get; set; }
        public virtual DbSet<LAB_HYDRATE_ANALYSIS> LAB_HYDRATE_ANALYSIS { get; set; }
    }
}
